### PR TITLE
Add benchmark folder

### PR DESCRIPTION
**Pull request by defunctzombie**
- mcap benchmark player loads messages and plays them with no delay
- memory layout provides pre-defined layouts to benchmakr

Run
```
yarn benchmark:serve
```

Open a browser and load an mcap file.

### CODE REVIEW

**Review by jtbandes — COMMENTED** [review]
Is it necessary to duplicate the webpack config and index.tsx?

**Comment by defunctzombie** [comment]
> Is it necessary to duplicate the webpack config and index.tsx?

"yes" - mostly cause I imagine taking benchmarks in a different build direction than _web_ folder goes. We might want to add some logs or other signals for automated tools. Its not strictly necessary but this is an easy thing to maintain separately.

**Comment by defunctzombie** [comment]
> Is this meant to be used totally manually or with some automation? It would be nice to add some docs (benchmark/README.md?) around this cause today I see a benchmark folder but I don't know what to do with it.

I am hoping with some automation but right now it is manual - but not entirely sure yet. This is very much a WIP idea that I published to see what folks thought. I see now that somehow it is not a draft PR.

**Comment by defunctzombie** [comment]
One thing I haven't figured out yet with this is why the 3d panel doesn't display anything  - or maybe it does and I don't see it fast enough.

**Pull request closed without merging**
