### PR TITLE
Fix handling of out of bounds urlState time values

### PR DESCRIPTION
**Pull request by foxymiles**
**User-Facing Changes**
Fix handling of out of bounds urlState time values.

**Description**
This makes two fixes:
1. Clamps the ranges supplied to the ProgressPlot component so it doesn't draw out of bounds.
2. Clamps the seek time in the `IterablePlayer` seekPlayback method within start & end time.

### CODE REVIEW

**Review by jtbandes — APPROVED** [review]
I think this is a helpful change, but not entirely sufficient. Something in the app was allowing the `&time` in the url to overwrite the data source's actual time bounds, which shouldn't be allowed regardless of whether it's being displayed in a ProgressPlot or some other kind of UI element.

**Comment by foxymiles** [comment]
@jtbandes I've also added a fix here to `IterablePlayer` which should handle the case of clamping seek time during initialization.

**Comment by foxymiles** [comment]
Incorporated some suggestions from @defunctzombie to make this more robust.

**Review by jtbandes — APPROVED** [review]

**Comment by jtbandes** [comment]
Forgot to ask earlier but are there some unit tests we can add around this for the player?

**Comment by foxymiles** [comment]
> Forgot to ask earlier but are there some unit tests we can add around this for the player?

Yes we probably should. I'll try to work that in this week.

**Pull request merged**
