### PR TITLE
Add editable title to Plot panel

### PR DESCRIPTION
**Pull request by 2metres**
**User-Facing Changes**
Screen Shot 2022-05-19 at 1 06 19 pm

**Description**

### CODE REVIEW

**Comment by 2metres** [comment]
@foxymiles having trouble updating the panel settings for the Input `onChange` event

**Comment by foxymiles** [comment]
@2metres All you have to do is change the config and the settings tree will automatically be rebuilt by the `useEffect` above the change handler:

```
  const handleTitleChange = useCallback(
    (event: ChangeEvent<HTMLInputElement>) => {
      saveConfig({ title: event.target.value });
    },
    [saveConfig],
  );
```

```
  useEffect(() => {
    updatePanelSettingsTree(panelId, {
      actionHandler,
      roots: buildSettingsTree(config),
    });
  }, [actionHandler, config, panelId, updatePanelSettingsTree]);
```

**Comment by 2metres** [comment]
Summarizing offline feedback from @amacneil:
> Plot title in toolbar should be only editable on double-click

**Comment by amacneil** [comment]
> Summarizing offline feedback from @amacneil:
> 
> > Plot title in toolbar should be only editable on double-click

Yeah, the "always editable" title feels off to me. I think we should either make it only editable in the settings, or double click to edit (or right click in the future once we sort out our context menu story). See what feels the most natural.

**Comment by foxymiles** [comment]
What if we put a little pen icon next to it that you click to go into edit mode?

**Comment by foxymiles** [comment]
@2metres @amacneil The problem with using double click to edit is that double click is already a standard interaction to select text. What if we show a pencil icon on hover that the user can click on to edit the title?

**Comment by amacneil** [comment]
Can we change the default name back to `Plot`?

I still find this interaction a little weird. Agree with @foxymiles point about double click already having an action, although selecting panel titles probably isn't very common.

I would be in favor of either just removing the inline edit (if you want to change the title you do it in the sidebar), or if we really want to keep double click to edit, then I think when you double click the title it should turn into something more obviously resembling a text input box (rather than just a tiny cursor appearing)

**Review by amacneil — APPROVED** [review]

**Pull request merged**
