### PR TITLE
Remove dataset iteration from PlotLegendRow

### PR DESCRIPTION
**Pull request by defunctzombie**
**User-Facing Changes**
None

**Description**
The Plot panel has a feature to display current and hovered values in the legend. This feature was implemented in https://github.com/foxglove/studio/pull/2484.

The logic for the feature computed the value by iterating through the dataset within the PlotLegendRow. This iteration would happen on every tick or during hovering. For large datasets, this iteration slows down rendering.

This change removes dataset iteration from the PlotLegendRow and uses the messages reducer already present in the plot panel to capture the latest value for each path.

Fixes: #2920

### CODE REVIEW

**Comment by kakaSheepA** [comment]
> **面向用户的更改** 无
> 
> **描述** Plot 面板具有在图例中显示当前值和悬停值的功能。此功能在#2484中实现。
> 
> 特征的逻辑通过遍历 PlotLegendRow 中的数据集来计算值。此迭代将在每个滴答声或悬停期间发生。对于大型数据集，此迭代会减慢渲染速度。
> 
> 此更改从 PlotLegendRow 中删除数据集迭代，并使用绘图面板中已经存在的消息缩减器来捕获每个路径的最新值。
> 
> 修复：#2920

111

**Comment by kakaSheepA** [comment]
> 存储库

**Comment by jtbandes** [comment]
Is this change still relevant and in need of review

**Comment by defunctzombie** [comment]
> Is this change still relevant and in need of review?

Yea - it is definitely relevant but iirc wasn't ready for review. Either way it has conflicts now that I should resolve.

**Comment by jtbandes** [comment]
I'll wait til conflicts are resolved in case that changes anything significant

**Pull request closed without merging**
