### PR TITLE
Make eslint config intellij friendly

### PR DESCRIPTION
**Pull request by foxymiles**
**User-Facing Changes**
None

**Description**
This converts our root eslintrc from yaml to JSON so we can use the `__dirname` variable. This is necessary for the sub packages to find tsconfig.eslint.json in the correct root path.

Related issue https://github.com/typescript-eslint/typescript-eslint/issues/251

### CODE REVIEW

**Review by snosenzo — APPROVED** [review]
I'm all for json over yaml

**Review by defunctzombie — DISMISSED** [review]
We have comments in our .eslintrc file and this change loses those. To me the comments outweight the benefit of json.

**Comment by snosenzo** [comment]
this is actually just a js file, so we should be able to transfer those comments over

**Comment by foxymiles** [comment]
I'll add the comments back.

**Comment by foxymiles** [comment]
Manually setting the eslint working directory to `./;` as described in one of the comments here seems to be a workaround if we prefer to keep the eslint rules in yaml.

https://youtrack.jetbrains.com/issue/WEB-47201/WebStorm-incorrectly-builds-the-path-to-eslints-parserOptionsproject-file-since-20202

**Comment by amacneil** [comment]
What's old is new again https://github.com/foxglove/template-typescript/pull/28

**Comment by foxymiles** [comment]
Closing this since it seems like there is a workaround and people like the yaml syntax. We can revisit if it seems to be a problem for people.

**Pull request closed without merging**
