### PR TITLE
[New3D] Don't auto-select a different frame if the user-configured render frame doesn't exist

### PR DESCRIPTION
**Pull request by jhurliman**
**User-Facing Changes**

- `3D (Beta)` panel will no longer auto-select a different frame if the user-selected frame does not exist

**Description**

Fixes https://github.com/foxglove/studio/issues/3863

### CODE REVIEW

**Comment by amacneil** [comment]
Seems to work.

There is a strange behavior that I guess the panel defaults to "auto" frame or something? Because if I start with a fresh new3D panel, load a bag file with `base_link` frame, then load a different bag file with no `base_link`, it will happily switch over to `world` frame automatically. But if I specifically change the frame then it will stay on what I selected.

The behavior seems reasonable, just want to check that it is intended.

**Comment by defunctzombie** [comment]
> There is a strange behavior that I guess the panel defaults to "auto" frame or something? Because if I start with a fresh new3D panel, load a bag file with `base_link` frame, then load a different bag file with no `base_link`, it will happily switch over to `world` frame automatically. But if I specifically change the frame then it will stay on what I selected.

I find this behavior still somewhat odd. I think the panel starting out in _auto_ mode is fine but once a frame is selected (and I see it in the `Display frame` it seems sensible that frame remains selected. I wonder if we should have an _auto_ option be explicit in the dropdown? You basically let the panel decide?

With no auto option the behavior that seems most "stable" to me is when you add a new 3d panel it is in frame discovery mode. Once you open some data the panel selects a suitable frame and that is what you see in the frame selection drop down. When this happens the panel does not go back to auto-discovery mode.

My reasoning is as follows: let's say I open a file for my robot. I want to view things in base_link and the 3d panel auto-selected that. I see `base_link` as the display frame and take no action to re-select it. I open another file and for some reason this file doesn't have the right transform information. Rather than being notified that some items can't render because we don't have `base_link`, I've been thrown into another frame - one that I don't view data in or want to use day-to-day.

**Comment by amacneil** [comment]
I actually found the current behavior pretty helpful. It means when you open a new file you have a good chance of the 3d panel working.

If we want to keep the current behavior but make it more explicit, we could add a menu entry like `Auto (base_link)` so we can show both the fact that you're in auto mode, and the current frame you're looking at?

**Comment by defunctzombie** [comment]
> I actually found the current behavior pretty helpful. It means when you open a new file you have a good chance of the 3d panel working.

When you open a file and it selects a strange frame (like camera front) and you are now inverted in the scene - "working" isn't quite the feeling. And I've definitely seen it happen where the panel puts you into a strange frame and view. Maybe we go with this for now and if I run across such examples I can remember to file issues for evidence over anecdotes.

**Comment by jhurliman** [comment]
> When you open a file and it selects a strange frame (like camera front)

Please file this as a bug with repro steps if possible. The auto-frame selection should only select a CAMERA_FRONT frame if there are no well-known frames and CAMERA_FRONT is the root frame of the largest tree of coordinate frames.

**Review by defunctzombie — APPROVED** [review]

**Pull request merged**
