### PR TITLE
Update readme badges

### PR DESCRIPTION
**Pull request by jtbandes**
**User-Facing Changes**
None

**Description**
Before

image

After

image

### CODE REVIEW

**Review by ocin-rye — APPROVED** [review]
Looks good!

**Comment by amacneil** [comment]
the `ROS 1 & 2 supported` one sort of implies to me that we are ros-specific. maybe drop that?

you could also add one for `version` if you want

**Comment by jtbandes** [comment]
I was thinking of making it more attractive to ROS users with the ROS badge, but if you think it makes it appear too ROS-specific, I'll drop that

**Comment by banisadr** [comment]
Looks good to me. Not strictly necessary, but is there a SO overflow badge? I really want to get that public knowledge base going.

**Review by banisadr — APPROVED** [review]

**Comment by jtbandes** [comment]
I'll let you make a PR if you desire to add another badge 😄

**Pull request merged**
