### PR TITLE
Use 13px base font size

### PR DESCRIPTION
**Pull request by amacneil**
**User-Facing Changes**
Font sizes are adjusted throughout the app to standardize on 13px for most text. See https://github.com/foxglove/studio/issues/1998 for rationale.

**Description**
- Various font sizes are configured in `src/theme/index.ts` and used throughout the app.
- `medium` corresponds to `13px` and used in most places
- Weird `xyzPlus` font variants are marked deprecated (some but not all are already marked deprecated in fluentui typedefs)
- Dialed back a few inconsistencies such as the Diagnostic Status panel heading font size

**Todo**
- Investigate: 3D panel buttons/icons got smaller for some reason

Closes https://github.com/foxglove/studio/issues/1998

**Before**
image

**After**
image

### CODE REVIEW

**Comment by defunctzombie** [comment]
My general feeling is that maybe we should go smaller with the default font size - 👍 to going with 13 and being consistent to start.

**Comment by 2metres** [comment]
This appears to break all icons

**Comment by 2metres** [comment]
That’s been off for a while now, likely unrelated to your change

**Comment by defunctzombie** [comment]
We want to switch to MUI and should revisit fonts and themes once we do that.

**Pull request closed without merging**
