### PR TITLE
Create events in studio

### PR DESCRIPTION
**Pull request by foxymiles**
**User-Facing Changes**
This makes it possible to create events directly from studio.

**Description**
Add support for creating events directly from studio.

Adds a new "Create Event" button to the playback bar and a new dialog for creating events.

https://user-images.githubusercontent.com/93935560/190419150-10b0930d-0a30-43c3-866a-96fa3d10788c.mov

### CODE REVIEW

**Comment by 2metres** [comment]
@foxymiles 
Remove time input and replace with current time in selected time format in the header
Move duplicate key error to be 1x at the bottom instead of next to each input but keep current highlight behavior

@2metres
Swap sec/nsec toggle to use MUI ToggleButtonGroup (instead of ButtonGroup :lol:)
Style Dialog to look less MUI-ey
Add -/+ at end of metadata row similar to console

**Comment by amacneil** [comment]
product review feedback:
- move the sales tag icon to the left
- change the icon to "bookmark add"
- remove the gray background when active, looks disabled
   image

**Comment by defunctzombie** [comment]
Great addition to the product!

**Review by defunctzombie — APPROVED** [review]

**Comment by amacneil** [comment]
I was excited to discover we shipped this feature during a customer demo last week 😄 Nice work!

**Pull request merged**
