### PR TITLE
Update readme structure, image header, and links

### PR DESCRIPTION
**Pull request by ocin-rye**
**User-Facing Changes**

Update readme structure, image header, and links

**Description**

Changes made:
- New header image, title, links, and badges
- The 'contribute' section has been moved above the 'self-host' section (Esther mentions that contribution is a higher priority and self-host)
- Two sets of vertical links sets have been changed to horizontal links to reduce page length

Thing(s) to consider:
- I've kept the existing repo description with the links as is, but they may be redundant with the newly added links: "[Foxglove Studio](https://foxglove.dev/) is an integrated visualization and diagnosis tool for robotics, available [in your browser](https://studio.foxglove.dev/) or for [download](https://foxglove.dev/download) as a desktop app on Linux, Windows, and macOS."

Addresses #4615 - Style uplift on Studio Readme

### CODE REVIEW

**Review by 2metres — APPROVED** [review]
👍 I like it! Looks great

**Comment by jtbandes** [comment]
I guess there’s probably not much that can be done to make the new header image look less small on mobile?

97D6B3C6-2DF1-4500-AF26-8B2996C39D25

**Comment by jtbandes** [comment]
Actually I wonder if we could use this media attribute with a min-width/max-width: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to

**Comment by jtbandes** [comment]
Wonder if it should be either “Accelerate Your Robotics Development” or “Accelerate your robotics development”? On the website homepage we use “Accelerate your **robotics** development” (purple).

**Comment by ocin-rye** [comment]
@jtbandes
- I'll take look and see if the media attribute is a possible solution for the image responsiveness. 
- Good catch, I'm in favor of correcting the title casing to read “Accelerate Your Robotics Development”, but using sentence case makes sense too for alignment with the homepage. @2metres  @esthersweon Any preferences or existing branding guidelines for this?

**Comment by jtbandes** [comment]
I think we have leaned towards sentence case for strings in our products, but not aware of any existing guidelines around web content

**Comment by ocin-rye** [comment]
Sounds good, I'll update to sentence case for now

readme-header

**Comment by jtbandes** [comment]
It would be awesome to add an equivalent image to the https://github.com/foxglove/mcap readme too, especially since we're about to present mcap at a conference so it'll be getting a lot more traffic 🔜!

**Comment by ocin-rye** [comment]
Uploading the mobile image to reference URL in the readme file

readme-header-mobile

**Comment by jtbandes** [comment]
Looks like there's some weird height mismatch issue at the top of that image

image

**Comment by ocin-rye** [comment]
I didn't see that in dark mode. This image should resolve it.
readme-header-mobile

**Comment by esthersweon** [comment]
I think it's a little strange that we only include "Web app" in the nav links, but then include links to both apps in the sentence. Could we just have "Download" in the nav link (https://foxglove.dev/download), which takes you to a page for both apps, or have both links in the nav?

That first sentence is also worded a little awkwardly (I'd recommend "available [in your browser](https://studio.foxglove.dev) or [as a desktop app](https://foxglove.dev/download)").

Screen Shot 2022-10-16 at 12 35 21 PM

**Comment by ocin-rye** [comment]
> I think it's a little strange that we only include "Web app" in the nav links, but then include links to both apps in the following sentence:
> 
> Screen Shot 2022-10-16 at 12 35 21 PM
> 
> Could we just have ["Download"](https://foxglove.dev/download) in the nav link to take you to a page for both apps, or have both links in the nav? Or maybe exclude both, since the first sentence takes care of calling out both?
> 
> That first sentence is also worded a little awkwardly (I'd recommend "available [in your browser](https://studio.foxglove.dev) or [as a desktop app](https://foxglove.dev/download)").

@esthersweon 👍 I've added this copy/link update

**Comment by defunctzombie** [comment]
Great stuff!

**Pull request merged**
