### PR TITLE
Stabilize the plot panel addMessages callback

### PR DESCRIPTION
**Pull request by foxymiles**
**User-Facing Changes**
None

**Description**
Stabilize the plot panel addMessages callback. This callback refers to our current loaded blocks time range but doesn't need to be invalidated when it changes so we can stabilize it by using a reference instead of a direct dependency.

### CODE REVIEW

**Review by jtbandes — COMMENTED** [review]
Why don’t we need to re-process the messages when the blocks time range changes?

**Comment by foxymiles** [comment]
> Why don’t we need to re-process the messages when the blocks time range changes?

Invalidating addMessages won't do that anyway. We'd need to toss the stuff we've accumulated across previous calls. The only case where this would be a problem is when blocks are loading slowly and the user hits playback in some part of the timeline not covered by a block though.

**Comment by foxymiles** [comment]
@jtbandes I think we're going to have to overhaul the way we accumulate and process messages in this panel soon anyway to address some of the performance issues with larger datasets.

**Review by defunctzombie — APPROVED** [review]
:D

https://github.com/foxglove/studio/pull/5694#discussion_r1167069108

**Comment by foxymiles** [comment]
> :D
> 
> [#5694 (comment)](https://github.com/foxglove/studio/pull/5694#discussion_r1167069108)

I should note that I haven't actually observed this to be a performance issue so the purpose of this PR is mainly to silence the warnings.

**Pull request merged**
