### PR TITLE
Delete some unused code around json primitives

### PR DESCRIPTION
**Pull request by defunctzombie**
**User-Facing Changes**
None

**Description**
JSON primitives are not a thing in ROS. This was a bespoke webviz-ism that we removed long ago. This cleans up some remnants that are no longer used.

FG-3297

### CODE REVIEW

**Comment by defunctzombie** [comment]
@jtbandes lets start with the code deletion we know we want to do and then can tackle what to do about logic changes or tweaks.

**Comment by jtbandes** [comment]
You’ve still got a bunch of build errors.

**Comment by defunctzombie** [comment]
> You’ve still got a bunch of build errors.

The json code is more invasive than anticipated

**Comment by jtbandes** [comment]
Missed a spot.

**Comment by defunctzombie** [comment]
The deletions will continue until morale improves

**Comment by jtbandes** [comment]
Chromatic's morale has not improved.

**Comment by defunctzombie** [comment]
@jtbandes morale is at an all time high

**Review by jtbandes — APPROVED** [review]

**Pull request merged**
