### PR TITLE
Add cache for layout storage

### LINKED ISSUE #3274: Loading layouts sometimes takes a long time
**Description**

When I open the Layouts side panel, sometimes it takes a few seconds for the layouts to load. Today, things were especially bad, with loading taking 30s or more at times.

https://user-images.githubusercontent.com/1159930/165590102-fe5833f9-9f52-4180-b7ee-24e55a058df3.mp4

This also happens after the Layout panel loads for the first time -- it looks like it gets refreshed periodically, and while it's refreshing, I can't switch to another layout.

- Version: 1.7.0
- OS: Ubuntu

**Steps To Reproduce**

I don't have nice clean steps to replicate here with a dummy setup, so I'll try to describe my real setup and what I'm seeing as best as possible.

* I am logged in with an account, and I have about ~50 personal layouts and about ~10 team layouts. Some of these layouts are fairly complicated.
* It looks like there's a request for `/layouts` that happens periodically, all of those are coming through quickly so it doesn't seem like a delay due to a remote server
   * Selection_999(511)
* I'm not seeing any obvious errors in the Console when this happens, though I do see some warnings, dunno if they're related
   * Selection_999(513)

The one thing I think is influential is the complexity of the currently loaded layout, and (possibly) the overall load on the computer too. For example, if I load a complex layout with lots of plots, then in general Studio becomes sluggish, including the processing of Layouts. Here's one example where i took the demo layout and duplicated a bunch of panels and added a plot panel. I'm able to get Studio processes to use a lot of CPU this way, and then when I open the Layouts side panel, it takes ~5s to load.

Selection_999(519)

I understand that high load on the running machine is out of your hands, but this can lead to frustration because if I made a layout "too complicated" then I can't switch out of it without having to reload everything. Perhaps one "fix" might be to have a setting about how often to refresh layouts, so I could lower that refresh rate in this situation? Or to not freeze the layouts panel and allow you to switch while it's being loaded? For example I tried logging out of my account so it would stop loading, but then all my layouts were gone. :shrug: 

I have a few videos of this behavior on the real setup if it's helpful, DM me in slack if you'd like to see them.

### PR DESCRIPTION
**Pull request by jtbandes**
**User-Facing Changes**
Improved performance of the Layouts sidebar with more caching.

**Description**
Alternative to #3557
Fixes #3274
Revival of/successor to code added in #1206 & removed in #1679

Marking as draft because we need to discuss the implications on using multiple Studio windows/tabs/instances. Currently the cache will not be reloaded during the whole session, which means changes in the underlying storage from another instance of the app will not be picked up. Is this acceptable?

### CODE REVIEW

**Review by foxymiles — APPROVED** [review]

**Comment by defunctzombie** [comment]
This is a draft PR - is this the final form or ready for review?

**Comment by defunctzombie** [comment]
Do we currently handle changing across multiple instances of the app?

I'm tempted to say that it is acceptable for now in the interest of improving this experience. I think our general strategy for data-sync needs some thought but we don't need to tackle that here.

**Comment by jtbandes** [comment]
Currently changes across multiple instances are not explicitly handled, but because we occasionally reload the whole cache, changes will eventually be picked up (not changes to your currently selected layout, but if you switch layouts)

**Comment by defunctzombie** [comment]
> Currently changes across multiple instances are not explicitly handled, but because we occasionally reload the whole cache, changes will eventually be picked up (not changes to your currently selected layout, but if you switch layouts)

Could we still re-load the whole cache in the background? Just not make that a blocker to interactive use?

**Pull request merged**
