### PR TITLE
Restack and style playback bar so Scrubber is above controls

### PR DESCRIPTION
**Pull request by 2metres**
**User-Facing Changes**
Screen Shot 2022-09-01 at 3 42 31 pm

Screen Shot 2022-09-01 at 3 42 45 pm

**Description**
Moves scrubber bar above playback controls, removes background color from buttons and styles Hover timestamp like other tooltips.

### CODE REVIEW

**Comment by defunctzombie** [comment]
I like it.

Using it in the preview deployment felt natural and not a massive break from today's setup. One thought that I had while actually using it with some data is whether the _time_ should go in the center of the screen under the scrubber (where the play and seek buttons are). My high level ux idea here is that the current playback time is actually an important part of the debug and diagnostic process and by putting it in the middle we allow a user to have easier focus on it without other elements distracting.

**Comment by 2metres** [comment]
@defunctzombie Not sure I 100% understand what you asking for here. You get a timecode just above your cursor when hovering the the scrubber similar to what you are describing. IMO Adding the number in the middle will increase the height of the bar to be far too tall.

I worked through several arrangements and I think having the playback in the bottom left and the controls in the middle works best of all the variations I tried.

**Comment by defunctzombie** [comment]
@2metres 

image

**Comment by amacneil** [comment]
👌

**Review by defunctzombie — APPROVED** [review]

**Pull request merged**
