### PR TITLE
Offline avatar handling

### PR DESCRIPTION
**Pull request by 2metres**
**User-Facing Changes**
Show default avatar when user is offline instead of missing image

**Description**
Detect when the user is offline and set the connection status in the WorkspaceContext. 

Resolves FG-3563

### CODE REVIEW

**Comment by 2metres** [comment]
I'm not 100% certain this is the right approach. But taking a stab anyways

**Comment by foxymiles** [comment]
I think this is worth exploring but it won't help with issues like https://github.com/foxglove/studio/issues/6062 where the user has an active wifi connection but can't reach the internet. For that we'd need some kind of liveness check that actually hits an internet endpoint.

**Comment by jtbandes** [comment]
> User-Facing Changes
> Detect when the user is offline and set the connection status in the WorkspaceContext.

The user-facing changes are meant to be used as an entry in the product release notes. A user who reads the release notes will have no idea what this means.

**Comment by defunctzombie** [comment]
https://medium.com/@abhishekmicosoft/handling-img-fallback-307653b2f30

We can use a pure html solution and inline a base64 image resource as the fallback. This lets the browser handle what happens if the image can't be loaded.

```
<object data="https://www.gravatar.com/avatar/00000000000000000000000000000000" type="image/jpeg">
  <img src="https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50" />
</object>
```

**Comment by 2metres** [comment]
Closed by #6308 6308

**Pull request closed without merging**
