### PR TITLE
Fix point hover logic on map panel

### PR DESCRIPTION
**Pull request by foxymiles**
**User-Facing Changes**
Fix logic to detect hovered points on map panel.

**Description**
Fix logic to detect hovered points on map panel. When we have a preview time the existing logic looks for the most recent point _before_ the hover time, which causes it to pick the point before the actual hovered point. The fix is to look for the most precent point _before or at_ the current hover time which includes the currently hovered point.

### CODE REVIEW

**Review by jtbandes — APPROVED** [review]

**Comment by foxymiles** [comment]
@esthersweon Can you please confirm that this fixes the issue you observed?

**Comment by jtbandes** [comment]
Can we add some kind of test for this?

**Comment by foxymiles** [comment]
> Can we add some kind of test for this?

Difficult but I can try. It might be one of those tests that tends to be flaky.

**Comment by esthersweon** [comment]
There are some instances where clicking on a point will still seek to the point before it – this feels like buggy behavior:

https://github.com/foxglove/studio/assets/6993359/e8f62c3d-8a88-477a-8eb2-87962ac3be52

**Comment by foxymiles** [comment]
I'm going to merge this since it's definitely an improvement on the behavior on main but will keep the ticket open to track further fixes.

**Pull request merged**
