### PR TITLE
feat multi local ros1 bag

### PR DESCRIPTION
**Pull request by BENcorry**
**User-Facing Changes**

When someone record bags with --split, could load them all at once.
**Description**
Resolve [[# 123](https://github.com/orgs/foxglove/discussions/123)]

### CODE REVIEW

**Comment by banisadr** [comment]
Hi @BENcorry thanks for the PR! This is something we certainly wanted to address in our backlog. A couple of criteria we want to meet before we can accept and merge this PR:

- Ensure its performant: Probably ensuring it can work with ~5 bags will cover ~95% of use cases for now
- Handling overlap: Make sure it handles overlapping bags gracefully with either one of:
    - Checks for non-overlap and raise a warning to the user if overlap exists (base case, probably easier)
    - Merges overlapping time ranges (probably where we want to end up, but not required for this PR)
- Checks for topic conflicts: Same topic with different schema raises a warning for the user
- Format Agnostic: Works with ROS1, ROS2, and MCAP. Does NOT need to handle multiple formats at the same time

**Comment by BENcorry** [comment]
Hi @BENcorry thanks for the PR! This is something we certainly wanted to address in our backlog. A couple of criteria we want to meet before we can accept and merge this PR:

Ensure its performant: Probably ensuring it can work with ~5 bags will cover ~95% of use cases for now
Handling overlap: Make sure it handles overlapping bags gracefully with either one of:
Checks for non-overlap and raise a warning to the user if overlap exists (base case, probably easier)
Merges overlapping time ranges (probably where we want to end up, but not required for this PR)
Checks for topic conflicts: Same topic with different schema raises a warning for the user
Format Agnostic: Works with ROS1 bag files and MCAP. Does NOT need to handle multiple formats at the same time

------------------------------------------------------------------------------------------------------------------

hi @banisadr.since I have not come into contact with files in MCAP format in my daily work, could u please provide some MCAP files for testing

**Comment by amacneil** [comment]
Here is an mcap file you can test with:

https://assets.foxglove.dev/NuScenes-v1.0-mini-scene-0061-8c50124.mcap

**Comment by banisadr** [comment]
Closing for now since this doesn't seem active, but can re-open in the future.

**Pull request closed without merging**
