### PR TITLE
studio-base package is public

### PR DESCRIPTION
**Pull request by amacneil**
**User-Facing Changes**
`@foxglove/studio-base` has been published at https://www.npmjs.com/package/@foxglove/studio-base

### CODE REVIEW

**Comment by amacneil** [comment]
@esthersweon adding `docs` label because we should add a readme to this package

**Comment by amacneil** [comment]
@defunctzombie this story is still flaking:

image

**Comment by defunctzombie** [comment]
What was flaky about it? The lines look in the same place? Were the lines a different color? Or off by 1px?

**Comment by amacneil** [comment]
@defunctzombie lines are missing entirely in second one:

https://www.chromatic.com/test?appId=603ec8bf7908b500231841e2&id=60f7bae804c39c003940adb3

**Pull request merged**
