### PR TITLE
Add user-defined custom geojson layer to map

### PR DESCRIPTION
**Pull request by jessicaaustin**
See https://github.com/foxglove/studio/issues/2284

### CODE REVIEW

**Comment by defunctzombie** [comment]
This is blocked on either exposing a _settings_ api to extensions panels (The builtin Map panel is authored via the extension api), or finding a UI within the panel to allow the user to setup the custom geojson layer.

**Comment by defunctzombie** [comment]
@jessicaaustin This came up in another context recently. The use case there was suggesting reading the GeoJSON from a topic rather than hard-coded into the panel settings. Wondering if that would be compelling or meet your use case too?

**Comment by jessicaaustin** [comment]
@defunctzombie Yes that would work as well, and probably a more flexible solution anyway for integrating into an existing system.

**Comment by defunctzombie** [comment]
Closing this out since we landed https://github.com/foxglove/studio/pull/3078 which allows you to send geojson data within messages on topics.

Please give it a try and send feedback!

Thanks for the initial prototype here and feedback.

**Pull request closed without merging**
