### PR TITLE
Add website iframe panel

### PR DESCRIPTION
**Pull request by jk-ethz**
Display external websites as an embedded iframe.

Solves #4800

Allows to embed great things, such as terminals or code editors.

image

### CODE REVIEW

**Comment by jk-ethz** [comment]
> @jk-ethz Thanks for putting this together. I think we should add this to the public extension marketplace rather than a built-in panel in the Studio source tree.

Why do you think so? Isn't an iframe panel something very basic that doesn't add much weight to the core bundle size?

**Comment by defunctzombie** [comment]
@jk-ethz yep! If you make a PR to: https://github.com/foxglove/studio-extension-marketplace your extension will show up in the extension marketplace sidebar.

**Comment by jk-ethz** [comment]
> @jk-ethz yep! If you make a PR to: https://github.com/foxglove/studio-extension-marketplace your extension will show up in the extension marketplace sidebar.

Cool, will do that once I have the time!

**Comment by jk-ethz** [comment]
When I try to install an extension, it tells me `Download the desktop app to use marketplace extensions.`
Is that something on the todo to get it working in the web app as well?

**Pull request closed without merging**
