### PR TITLE
Delete Select / Option component (only used in TopicSettingsEditor)

### PR DESCRIPTION
**Pull request by esthersweon**
**User-Facing Changes**
- Slightly different look to dropdown menus for point shape and point field in the 3D panel's Topic Settings Editor (more consistent with rest of app now)

**Description**
- Replaced instances of `Select` / `Option` with `Dropdown` / `DropdownItem` instead
- Deleted `Select` / `Option` components
- TODO: Replace `Dropdown` component with Fluent UI component across codebase, cc: @2metres 

Screen Shot 2021-07-23 at 9 26 34 AM

Screen Shot 2021-07-23 at 10 01 52 AM

Addresses part of https://github.com/foxglove/studio/issues/1426 (for `Select` and `Option`)

### CODE REVIEW

**Comment by defunctzombie** [comment]
Screenshot?

Will those two items of #1426 be closed out by this or will they have outstanding work?

**Comment by jtbandes** [comment]
The ultimate goal is to delete Dropdown as well in favor of FluentUI – but this seems like a relatively minimal change for a bunch of deleted code 👍 🔪 

Are there no storybook screenshots covering this? We need to get some at some point...

**Comment by esthersweon** [comment]
@defunctzombie - Added screenshot to PR description, and storybook tests to PR. Those 2 items (`Select` and `Option`) will be closed out with this PR.

@jtbandes - Mentioned that TODO in the PR description; agree that this is a minimal change that 🔪 s a lot of code and will make that later work easier.

**Comment by defunctzombie** [comment]
image

LGTM

**Pull request merged**
