### PR TITLE
chore(mcap-support): rename method to `deserialize`

### PR DESCRIPTION
**Pull request by jon-chuang**
**User-Facing Changes**
None

**Description**
rename deserialization method to `deserialize`

### CODE REVIEW

**Comment by defunctzombie** [comment]
chatgpt has spoken the true words

image

**Review by jtbandes — APPROVED** [review]
Doesn't seem like a significant improvement, but not harmful 🤷

**Comment by jon-chuang** [comment]
Hehe well, to me, it was a lot less clear before if calling deserializer would return a deserializer, or the deserialized object.


Chatgpt seems a little kooky about this.

**Comment by jtbandes** [comment]
> calling `deserializer` would return a deserializer

One way of thinking about it is that the `deserializer` property holds a deserializer.

**Comment by jon-chuang** [comment]
> One way of thinking about it is that the deserializer property holds a deserializer.

Yes, but it does not in fact, since the deserializer is actually either some external object referenced by the `deserialize` pointer...

The API may have been clearer, if more verbose, if `deserializer` stored an object with method `deserialize`...

**Pull request merged**
