### PR TITLE
Add toggle to disable zoom scrolling in StateTransitions panel

### PR DESCRIPTION
**Pull request by 2metres**
**User-Facing Changes**
Allow user to disable Scroll to zoom behavior on State Transtition panel

Screen Shot 2023-03-28 at 9 40 13 pm

**Description**
Related to #5592 and #5593

### CODE REVIEW

**Comment by defunctzombie** [comment]
Is the default config applied if there is already a config? I'm wondering if folks that have this panel will end up with a panel that has scroll zoom disabled after this change.

Is there something we can do that does not require the user to manually configure such a setting? Or surface this interaction to the panel as a sort of zoom or scroll lock?

It feels award to me that I'd need to adjust this setting depending on whether I've resized some of my other panels. Nothing in the failed user interaction reported in those tickets would make me think to go find this setting.

**Comment by 2metres** [comment]
This does not change the default behavior just introduces the option to disable zooming. Plot syncing and zooming still works, quite wll IMO because the chart only allows zoom not scroll. 

I would like to introduce a way to reset the zoom from within the panel/panel settings. However, it's entangled the TimeBasedChart component and chart syncing.

**Comment by 2metres** [comment]
> It feels award to me that I'd need to adjust this setting depending on whether I've resized some of my other panels. Nothing in the failed user interaction reported in those tickets would make me think to go find this setting.

🤷 We could introduce a button in the PanelToolbar?

**Comment by 2metres** [comment]
Closing based on feedback from team

**Pull request closed without merging**
