### PR TITLE
Change studio_msgs/ImageMarkerArray to visualization_msgs/ImageMarkerArray

### PR DESCRIPTION
**Pull request by jhurliman**
This matches the rosmsg-msgs-common package that was recently added

### CODE REVIEW

**Comment by amacneil** [comment]
Do you think we should support a non-standard message under `visualization_msgs` before it is accepted upstream?

Ref https://github.com/ros/common_msgs/pull/172

**Comment by jhurliman** [comment]
@amacneil now that we package our own `.msg` files in the repo I think we have more flexibility to run ahead of `ros/common_msgs`. We can tell end-users to vendor our copy of the `visualization_msgs/ImageMarkerArray` msg file into their repo for now. If we follow the model of browser vendors, we could support both `visualization_msgs/ImageMarkerArray` and the alias `foxglove_msgs/ImageMarkerArray` (presumably we would support this alias across more than just the Studio product in the future).

**Comment by defunctzombie** [comment]
I do not think we should be using an upstream package name from ros for a message that does not exist in that upstream package. This is confusing since we are not the authority on the visualization_msgs package and it isn't clear this message will be accepted. If you now go lookup the visualization_msgs package you won't find this message there. We should avoid such strangeness and collisions.

**Comment by amacneil** [comment]
Bump on this since it was merged but still needs discussing

**Comment by defunctzombie** [comment]
@jhurliman I think its best to change back to studio_msgs

**Pull request merged**
