### PR TITLE
Put legacy 3D panel behind feature flag

### PR DESCRIPTION
**Pull request by jtbandes**
**User-Facing Changes**
The 3D (Legacy) panel can no longer be added as a new panel. For now, it can still be re-enabled under the Experimental Features section of the Preferences tab. In the near future, it will be completely removed (#4450).

image

**Description**

Closes https://github.com/foxglove/studio/issues/4543

### CODE REVIEW

**Review by defunctzombie — APPROVED** [review]
This will merge this week after we've cut another release so that it is in the next release or do we plan to wait until later in October to merge?

**Review by jhurliman — APPROVED** [review]

**Comment by jtbandes** [comment]
Blocked by #4540

**Comment by amacneil** [comment]
The new release is out so this can be merged any time this week (before the 10/17 release).

We should only hide 3D Legacy from the panel list, it should otherwise continue working as usual for now. When you enable the feature flag we restore it to your panel list.

**Comment by defunctzombie** [comment]
:shipit:

**Pull request merged**
