### PR TITLE
Add tooltip to 3d floating buttons

### PR DESCRIPTION
**Pull request by 2metres**
**User-Facing Changes**
None

**Description**
Use MUI tooltip instead of native title element

https://github.com/foxglove/studio/assets/924528/b14006a0-e979-4a03-b578-f9673f0d0c36

### CODE REVIEW

**Comment by defunctzombie** [comment]
The reason we hadn't done this before is because the mui tooltip has very poor performance for re-rendering when we last profiled it and I am hesitant to add another use of it in a location that renders at 60fps. Have we fixed these performance concerns?

**Review by defunctzombie — DISMISSED** [review]
See comment about performance concerns. Convince me this is ok to add to a panel rendering at 60fps.

**Comment by 2metres** [comment]
Do we have something documenting the how to test the performance benchmarks that we need to pass for this?

**Comment by 2metres** [comment]
Throwing a tooltip around a button in the ui-benchmarking tool certainly doesn't bode well. 

Screen Shot 2023-12-21 at 9 09 40 am

**Comment by jtbandes** [comment]
One would hope that the `RendererOverlay` is not re-rendering at 60fps, during panning or playback. I am not saying I know for sure it doesn't – just that I would _hope_ it doesn't 😅

**Comment by 2metres** [comment]
> One would hope that the `RendererOverlay` is not re-rendering at 60fps, during panning or playback. I am not saying I know for sure it doesn't – just that I would _hope_ it doesn't 😅

From memory this should be true. But I also have no way of testing this

**Comment by 2metres** [comment]
From what I can tell the RendererOverlay does not re-render at 60fps. I think this PR is safe to merge.

**Review by defunctzombie — APPROVED** [review]
👍

Unrelated to the PR but it would be nice to find ways of using smaller component files for some of these things. It would make it more obvious which components use what state and selectors and what will cause them to re-render. I think we should be doing that across the codebase more.

**Pull request merged**
