### PR TITLE
Add <link rel=canonical /> tag with canonical URL to web build

### PR DESCRIPTION
**Pull request by esthersweon**
**User-Facing Changes**
- None

**Description**
- In response to ahrefs.com site audit:
   Screen Shot 2021-11-15 at 6 23 50 PM
- Added <link rel=canonical /> tag with canonical URL to web build

### CODE REVIEW

**Comment by jtbandes** [comment]
What are the duplicate urls that it detected?

**Comment by amacneil** [comment]
@esthersweon this doesn't seem like a good idea. When we add URL params support (https://github.com/foxglove/studio/issues/2025) this is going to be incorrect.

Per Jacob's question, what are the duplicate URLs? There shouldn't be any.

**Comment by jtbandes** [comment]
> When we add URL params support (#2025) this is going to be incorrect.

Are you sure? I don't think we would really want search engines indexing different sets of url params as different resources, would we?

**Comment by amacneil** [comment]
Hmm. Not sure - I don't think we should care about SEO for studio.foxglove.dev anyway. People might link to public datasets, but I don't know that we care if google indexes them or not.

The other thing to consider is that people might host studio on different domains, so it seems a bit weird hard coding our fqdn here? Maybe it's ok.

**Comment by esthersweon** [comment]
@jtbandes @amacneil - Hm it seems like it's seeing the URL with and without query params as different URLs (i.e. `studio.foxglove.dev` and `studio.foxglove.dev/?demo`).

Screen Shot 2021-11-16 at 4 55 54 PM

According to [this resource](https://webmasters.stackexchange.com/questions/114622/should-query-strings-be-included-or-removed-from-the-canonical-tag), if different query params give you different content, their canonical URLs should include the query strings.

**Comment by amacneil** [comment]
I see. I don't know whether we want to treat those as the same "content" then.

They have different content, even if a web crawler might not think so.

I don't know that this really matters either way, unless we start seeing search engines using the wrong URL as the "default".

**Comment by esthersweon** [comment]
@amacneil - that makes sense; will revert this PR.

**Pull request merged**
