### PR TITLE
Animate sidebar opening/closing

### PR DESCRIPTION
**Pull request by jtbandes**
**User-Facing Changes**
Added animation when opening/closing the sidebar.

**Description**
The sidebar opening/closing is a major UI shift. An animation helps the eye track what is changing and reduce confusion.

https://user-images.githubusercontent.com/14237/175134214-666d2071-cce8-414b-8c90-6ce4bb31b507.mov

### CODE REVIEW

**Comment by foxymiles** [comment]
Kind of mixed feelings about this. It looks nice but I wonder if it might become annoying for heavy users. I think I'd reduce the duration at least.

**Comment by defunctzombie** [comment]
What's the status of this? Do we intend to push this along or do we want to close this out as not planned?

**Comment by jtbandes** [comment]
I would like to pursue it. Now that we have moved off the old 3d panel, maybe that has resolved some of the flickering issues that were raised.

**Comment by jtbandes** [comment]
That said, maybe with mixed feedback and more changes needed it is not worth the effort. 🤷

**Pull request closed without merging**
