### PR TITLE
[New3D] Scale label offset with labelScale

### PR DESCRIPTION
**Pull request by snosenzo**
**User-Facing Changes**
 - n/a

**Description**
 - add .1 of labelScaleFactor to offset of FrameAxes labels

- followup from https://github.com/foxglove/studio/pull/4256

### CODE REVIEW

**Comment by jtbandes** [comment]
For changes like these with visual results, it would be nice to include a before/after screenshot in the PR summary. Although I guess we might get one from Storybook :)

**Comment by snosenzo** [comment]
oh I think this is covered in https://github.com/foxglove/studio/pull/4262

**Comment by jhurliman** [comment]
Compare with https://github.com/foxglove/studio/pull/4262

**Comment by snosenzo** [comment]
covered in https://github.com/foxglove/studio/pull/4262

**Pull request closed without merging**
