### PR TITLE
call service panel list all supported services

### PR DESCRIPTION
**Pull request by smbera**
**User-Facing Changes**

**Description**

List all supported services

In the past, I needed to remember the service name and request before I could call the service correctly. But there are so many service names and requests that I can't remember them all. This feature can list all the service names supported by the currently connected robot. After the user selects a service name, the corresponding request prompt will appear. He only needs to modify the value to correctly call the service.

https://github.com/foxglove/studio/assets/23401125/03a6dbe3-ff7a-4707-95dc-e14cc8b58ffa

### CODE REVIEW

**Review by jtbandes — CHANGES_REQUESTED** [review]
I appreciate the contributions, however, it's difficult to review changes like this when no context or description is provided. The video helps, but in order to move forward we are going to need a complete PR description that provides background information about what you are trying to achieve.

**Comment by defunctzombie** [comment]
Thanks for proposing these changes but as @jtbandes noted we can't accept this in its current form and lack of description to aid review. If you no longer have time to work on this that's understandable and we can close it until you have time to revisit so it doesn't go stale.

**Comment by smbera** [comment]
> I appreciate the contributions, however, it's difficult to review changes like this when no context or description is provided. The video helps, but in order to move forward we are going to need a complete PR description that provides background information about what you are trying to achieve.

In the past, I needed to remember the service name and request before I could call the service correctly. But there are so many service names and requests that I can't remember them all. This feature can list all the service names supported by the currently connected robot. After the user selects a service name, the corresponding request prompt will appear. He only needs to modify the value to correctly call the service.

**Comment by smbera** [comment]
> I appreciate the contributions, however, it's difficult to review changes like this when no context or description is provided. The video helps, but in order to move forward we are going to need a complete PR description that provides background information about what you are trying to achieve.

Thanks for proposing these changes but as @jtbandes noted we can't accept this in its current form and lack of description to aid review. If you no longer have time to work on this that's understandable and we can close it until you have time to revisit so it doesn't go stale.

**Comment by smbera** [comment]
> In the past, I needed to remember the service name and request before I could call the service correctly. But there are so many service names and requests that I can't remember them all. This feature can list all the service names supported by the currently connected robot. After the user selects a service name, the corresponding request prompt will appear. He only needs to modify the value to correctly call the service.

In the past, I needed to remember the service name and request before I could call the service correctly. But there are so many service names and requests that I can't remember them all. This feature can list all the service names supported by the currently connected robot. After the user selects a service name, the corresponding request prompt will appear. He only needs to modify the value to correctly call the service.

**Comment by smbera** [comment]
> Thanks for proposing these changes but as @jtbandes noted we can't accept this in its current form and lack of description to aid review. If you no longer have time to work on this that's understandable and we can close it until you have time to revisit so it doesn't go stale.

In the past, I needed to remember the service name and request before I could call the service correctly. But there are so many service names and requests that I can't remember them all. This feature can list all the service names supported by the currently connected robot. After the user selects a service name, the corresponding request prompt will appear. He only needs to modify the value to correctly call the service.

**Comment by achim-k** [comment]
@smbera thanks for your contirbution but as already mentioned above, we can't accept this PR in it's current form. If you want to implement this feature and get this PR accepted, you have to follow existing conventions and expose the list of services and datatypes through the render state such that it can be _watched_ for in the extension context. This also includes adding tests, cleaning up any lint errors and addressing other comments. Please comment here if you are willing to do this, otherwise we will consider this PR stale and close it soon.

**Comment by achim-k** [comment]
Closing due to inactivity

**Pull request closed without merging**
