### PR TITLE
Convert KeyListener to function component.

### PR DESCRIPTION
**Pull request by foxymiles**
**User-Facing Changes**
This should be transparent to end users.

**Description**
This converts `KeyListener` into a functional component.

Part of https://github.com/foxglove/studio/issues/1426.

### CODE REVIEW

**Comment by jtbandes** [comment]
It might be better to convert this to a hook like useKeyListener, or just replace it with existing hooks from `react-use` (or a plain useEffect + addEventListener) if it doesn't feel like it's used in enough places to be worth maintaining a custom hook

**Comment by foxymiles** [comment]
@jtbandes It looks like this in some cases depends on rendering a new div and attaching a listener to that. Would we be able to duplicate that functionality in a hook? I guess it would if we changed it to require the parent element as a parameter.

**Comment by jtbandes** [comment]
Right... the way I've usually seen this done with hooks is that the hook returns a ref which you can then attach to your desired element. For example: https://github.com/streamich/react-use/blob/master/docs/useScratch.md

**Comment by foxymiles** [comment]
@jtbandes I wonder if it would be worth deprioritizing converting this component? That feels like a lot of changes for a small benefit.

**Comment by defunctzombie** [comment]
LGTM

**Comment by defunctzombie** [comment]
Still planning to merge this?

**Comment by foxymiles** [comment]
> Still planning to merge this?

I was a little gun shy on this one since it seemed like the benefit was small and possible breakage was significant but I'll test it some more and merge it.

**Comment by defunctzombie** [comment]
We can also punt on it if we want to. I agree its not critical but also seemed like it was done. I think the merge conflict is some fix I put into KeyListener around modifier keys.

**Comment by foxymiles** [comment]
@defunctzombie I fixed the merge conflict and tidied this up a touch. It's working in my testing.

**Comment by defunctzombie** [comment]
:shipit:

**Pull request merged**
