### PR TITLE
Change cog icon to menu icon in panel toolbar

### PR DESCRIPTION
**Pull request by defunctzombie**
**User-Facing Changes**

Change the panel toolbar cog icon to a menu icon.

| Before | After |
| --- | --- |
|Screen Shot 2022-01-10 at 8 53 55 PM|Screen Shot 2022-01-10 at 8 54 04 PM|

**Description**
The menu icon is more appropriate for this action because it opens a context menu. This better aligns the icon with the action.

### CODE REVIEW

**Review by jhurliman — APPROVED** [review]

**Comment by 2metres** [comment]
Semantically I agree that the dropdown is a menu but I feel like the cog icon when next to the drag handle and the full screen icon is less ambiguous than the three lines icon.

**Comment by defunctzombie** [comment]
> Semantically I agree that the dropdown is a menu but I feel like the cog icon when next to the drag handle and the full screen icon is less ambiguous than the three lines icon.

@2metres Do you have a recommendation for icons that would make more sense? I dislike the cog serving the purpose of a context menu.

**Comment by defunctzombie** [comment]
Closing this per @2metres recommendation that the menu icon is too similar to the drag handle and other icons in the toolbar.

**Comment by defunctzombie** [comment]
I've changed the tooltip name here: https://github.com/foxglove/studio/pull/2665

**Pull request closed without merging**
