### PR TITLE
Add setCurrentLayoutData to CurrentLayoutContext

### PR DESCRIPTION
**Pull request by defunctzombie**
**User-Facing Changes**
None

**Description**
setCurrentLayoutData allows setting the data and replaces any existing data for the active layout.

### CODE REVIEW

**Review by foxymiles — COMMENTED** [review]
What is this used for?

**Comment by defunctzombie** [comment]
> What is this used for?

Nothing yet but it will be used for new code paths for layout storage.

**Review by jtbandes — APPROVED** [review]
💮

**Comment by defunctzombie** [comment]
Based on my latest spike I don't think I want this as written.

**Pull request closed without merging**
