### PR TITLE
Fix issue with Selected Point button positioning

### PR DESCRIPTION
**Pull request by 2metres**
**User-Facing Changes**
Selected point now appears in the not incorrect place

**Description**
Fix issue with Selected Point button positioning and refactor to use makeStyles

Screen Shot 2023-03-07 at 3 29 44 pm

### CODE REVIEW

**Comment by jtbandes** [comment]
"refactor to use makeStyles" is not a user-facing change

**Review by defunctzombie — APPROVED** [review]
"correct place" has a pretty open meaning :D 

I personally find it "incorrect" that two icons are at separate corners.

**Comment by 2metres** [comment]
Updated comment to satify @defunctzombie

**Comment by jtbandes** [comment]
@2metres User-facing changes is "cute" but please remember that this section of the PR is gathered up and put into our release notes that our customers will read. So it's better to put nothing at all than something that will confuse people. Keep the "cute" comments in the Description section 😄

**Pull request merged**
