### PR TITLE
Implement settings number field scrubbing

### PR DESCRIPTION
**Pull request by foxymiles**
**User-Facing Changes**
This allows users to click and drag on number values in the settings editor to set the value interactively.

**Description**
This is a pretty straightforward implementation that relies on pointer capture.

https://user-images.githubusercontent.com/93935560/186478245-949641ad-30a6-4894-8d8f-c8d097e64427.mov

### CODE REVIEW

**Comment by jtbandes** [comment]
This is cool, but makes it impossible to use the regular drag to select text in the field...

**Comment by foxymiles** [comment]
> This is cool, but makes it impossible to use the regular drag to select text in the field...

That's a tradeoff blender makes too. You can still double click to select all.

**Comment by jtbandes** [comment]
Two more bugs: doesn't work when field is empty, and is very susceptible to floating point precision issues. This is an Image panel settings:

https://user-images.githubusercontent.com/14237/186486642-42dd40a5-db47-4477-99b9-320a0cba6113.mov

**Comment by foxymiles** [comment]
@jtbandes Thanks I'll fix the empty case. For the precision issue I recommend using the `precision` field of the number input.

**Comment by jtbandes** [comment]
>  For the precision issue I recommend using the `precision` field of the number input.

Maybe we need a default precision then? I don't think this should be the default behavior.

**Comment by wimagguc** [comment]
When the user is done with dragging the input, the cursor is where they left off:

https://user-images.githubusercontent.com/349687/186524006-84811fbd-c188-4318-bdcd-8b71938b58ad.mov

**Comment by amacneil** [comment]
- need to fix step / rounding issue
- need to either show cursor, or keep it hidden and enable pointer lock while dragging (so that the cursor stays in place when you release)
- dragging inputs in 3d panel seems completely broken

**Comment by foxymiles** [comment]
> * need to fix step / rounding issue

Changed this to set a default precision of 2 if none is specified.

> * need to either show cursor, or keep it hidden and enable pointer lock while dragging (so that the cursor stays in place when you release)

Changed this to just show the <-> cursor instead of trying to lock the pointer.

> * dragging inputs in 3d panel seems completely broken

We may need to disable this for new3d for now.

**Comment by foxymiles** [comment]
> In Blender, when the user is done dragging, the cursor stays over the input:

Thanks for posting this. Given the downsides of pointer lock in the browser I think I'll just show the <-> cursor instead.

**Comment by amacneil** [comment]
Read only fields should hide the scrub icon and arrows
image

**Comment by foxymiles** [comment]
> Read only fields should hide the scrub icon and arrows

This should be fixed now.

**Review by defunctzombie — APPROVED** [review]

**Pull request merged**
