### PR TITLE
Improve playback performance with state transition panel

### PR DESCRIPTION
**Pull request by shuhaowu**
**User-Facing Changes**

Improve playback performance with state transition panel

**Description**

The `StateTransitions` panel creates the chartjs datasets from either block data ("horizontal" data) or "vertical"/instantaneous data. This dataset is memo'ed in React based on both the horizontal data (`decodedBlocks`) and the vertical data (`itemsByPath`).  This memo is necessary because creating the dataset can be a time consuming operation (~10-15ms).  Since the vertical data can change every frame, this means the chartjs datasets are being recreated every frame in the memo.  This is not a good idea because most of the time, the memo doesn't even use `itemsByPath` as all data is coming from blocks (as it should? this is a horizontal panel).  This change is a quick "fix" for the problem where we do not recompute the datasets if no paths are using the vertical data and all paths are using the horizontal data. The fix is not ideal, and the reason is given in the code comments. 

I've tried to split the `useMemo` into two memos: one for `itemsByPath` and another for blocks, but the resulting code is even worse. A bigger rework may be needed here but I'm looking for advise on how to proceed.

Collectively, this is taking ~15-20% CPU time and delays every frame by 10-15ms:

image

### CODE REVIEW

**Comment by foxymiles** [comment]
Thanks for the detective work and the fix! What kind of machine are you doing these measurements on?

**Comment by foxymiles** [comment]
I think your fix makes sense here. I've tidied up the logic a bit in this branch. Does this seem ok to you?

https://github.com/foxglove/studio/tree/miles/state-transition-memo-fix

**Comment by foxymiles** [comment]
@shuhaowu Yes I think you're right this separation is not ideal. And I may have to break this separation to fix another issue that's come up so this might only be a stopgap fix.

**Comment by defunctzombie** [comment]
> My impression is that, ideally, all data should be loaded via `decodedBlocks` so the entire history can be loaded all at once.

If the preloading buffers get full then you run into a situation where no more data is plotted. This depends on the preloading approach which we recently changed to preload from start rather than constantly change where we preload from.

See https://github.com/foxglove/studio/issues/5500 for a related issue this surfaced and some of the notes I left on this around what our reasoning for the change was.

**Comment by foxymiles** [comment]
@shuhaowu I've updated my https://github.com/foxglove/studio/tree/miles/state-transition-memo-fix to incorporate your fix and also merge in the current main brain so it can be merged back to main. Do you want to pull this into your PR here so we can merge it or would you prefer I open a separate PR on my branch we can merge? In either case you'd get contribution credit on the commit.

**Comment by foxymiles** [comment]
Incorporated into https://github.com/foxglove/studio/pull/6008. Thanks @shuhaowu !

**Pull request closed without merging**
