### PR TITLE
Refactor RawMessagePanel to use MUI styling and simplify logic

### PR DESCRIPTION
**Pull request by 2metres**
**User-Facing Changes**
Improves text readability for light mode users on JSON reader 

**Description**
Remove uses of foxglove/Icon component from RawMessagePanel and simplify logic

### CODE REVIEW

**Comment by foxymiles** [comment]
@2metres The shortcut to open a line chart from an item in the message doesn't seem to be working for me.

**Comment by 2metres** [comment]
> The shortcut to open a line chart from an item in the message doesn't seem to be working for me.

Good catch @foxymiles, one too many nested anonymus functions

**Review by foxymiles — APPROVED** [review]

**Comment by jtbandes** [comment]
@2metres can you also include this fix for #3846 in your PR as you see fit? https://github.com/foxglove/studio/pull/3857

**Review by defunctzombie — APPROVED** [review]
Please check the nesting arrow stuff that @jtbandes references in his closed PR.

**Review by defunctzombie — CHANGES_REQUESTED** [review]
No more muiStyled please 🙏

**Review by defunctzombie — APPROVED** [review]

**Pull request merged**
