### PR TITLE
Update sample dataset to use nuscenes2mcap

### PR DESCRIPTION
**Pull request by jtbandes**
**User-Facing Changes**
Updated the dataset used for "Explore sample data". The file size is reduced, and the dataset demonstrates more features of Studio, such as foxglove.SceneEntity and foxglove.Grid types, and support for MCAP files with mixed encodings (ROS, Protobuf, and JSON). The time-ordering of messages in the sample data has also been improved.

**Description**
Closes https://github.com/foxglove/studio/issues/2999

### CODE REVIEW

**Comment by amacneil** [comment]
Something is horribly wrong...

https://user-images.githubusercontent.com/637671/194462049-dbc490e5-c542-4435-9fb9-db72cd0bb470.mp4

**Comment by jtbandes** [comment]
Does it still do that after preloading has finished?

**Comment by amacneil** [comment]
Yes*

*but we only preload half the file, so I have to lag-play through it before I can get sane performance.

https://user-images.githubusercontent.com/637671/194463202-71f9bd08-abe7-440c-a890-2f8e469b64db.mp4

**Comment by snosenzo** [comment]
the drivable area isn't on by default but it should have these defaults instead of colormap: turbo
image

**Comment by jtbandes** [comment]
I've removed the re-publishing of the map, so that should help reduce stuttering once preloaded, but it looks like preloading is bottlenecked on ImageAnnotation deserialization. #4538 should help.

**Comment by amacneil** [comment]
Suggestions
- Hide `map` transform
- Show `/CAM_FRONT/image_rect_compressed` and `/CAM_FRONT/camera_info` at 2m distance

**Comment by amacneil** [comment]
Blocked on making sure we are not going to revert https://github.com/foxglove/studio/pull/4538

cc @defunctzombie

**Review by defunctzombie — APPROVED** [review]

**Pull request merged**
