### PR TITLE
Improve contrast in fluent theme

### PR DESCRIPTION
**Pull request by amacneil**
Before:
Screen Shot 2021-05-14 at 11 15 58 AM

After:
Screen Shot 2021-05-14 at 11 49 06 AM

(not sure why connection picker icons don't follow the sidebar icon colors, but that seems like a separate issue)

### CODE REVIEW

**Comment by jtbandes** [comment]
Screenshot

**Comment by defunctzombie** [comment]
I am all for improved contrast. My eyes are not what they use to be.

**Comment by amacneil** [comment]
> Screenshot
you're too fast 😜

**Comment by jtbandes** [comment]
> not sure why connection picker icons don't follow the sidebar icon colors

It looks like your "dark"/"light" direction has swapped - was that intentional?

**Comment by amacneil** [comment]
> It looks like your "dark"/"light" direction has swapped - was that intentional?

Not sure exactly what you mean, but after you made this comment I slightly fixed the theme colors by triggering onchange in the theme designer.

**Comment by jtbandes** [comment]
I meant that `themeLighter` used to be bright and `themeDarker` used to be dark, and now they have switched. Maybe that is correct because we use an inverted theme - I'm not sure.

**Comment by amacneil** [comment]
Well, our `white` is dark and our `black` is light, so I think that's intentional. At least that is what the theme builder generated for me.

**Pull request merged**
