### PR TITLE
Toggle experimental latching feature on by default

### PR DESCRIPTION
**Pull request by defunctzombie**
**User-Facing Changes**
Users of bag, mcap, and data platform sources are opted-into a new playback mode which improves message lookup when seeking by fetching the last message on all subscribed topics even if they occured many seconds or minutes before the seek location.

**Description**
The experimental latching feature enables a new playback mode for bag, mcap, and data platform sources. This playback mode backfills subscribe topics with the last message on each topic during a seek. This allows for panels to display data from infrequently published topics which improves seeking behavior.

Fixes: #3897

### CODE REVIEW

**Review by amacneil — APPROVED** [review]
🆒

**Comment by defunctzombie** [comment]
This is blocked on finding a solution to https://github.com/foxglove/studio/issues/3911. I am unhappy with the end-user behavior today for preloaded data.

**Comment by defunctzombie** [comment]
Blocke by: https://github.com/foxglove/studio/pull/3921

**Comment by amacneil** [comment]
ready to ship?

**Comment by defunctzombie** [comment]
Blocked on https://github.com/foxglove/studio/pull/3934 and https://github.com/foxglove/studio/issues/3949

**Comment by amacneil** [comment]
Glorious future

**Pull request merged**
