### PR TITLE
[3D] add user setting to enable logarithmic depth buffer

### PR DESCRIPTION
**Pull request by jtbandes**
**User-Facing Changes**
[3D] Added a setting to allow using a [logarithmic depth buffer](https://threejs.org/examples/#webgl_camera_logarithmicdepthbuffer), which can improve rendering quality for certain data.

**Description**
Relates to #4641, #4647

https://user-images.githubusercontent.com/14237/196515291-4e172183-407e-4402-bdff-253e6810682b.mov

### CODE REVIEW

**Comment by jtbandes** [comment]
Hmm, why does it degrade the quality of labels? Is that expected or something we're doing wrong with our label rendering?

**Review by snosenzo — APPROVED** [review]
works great! the only thing I kinda wish was that the logarithmic depth buffer toggle second or third in the list of camera settings next to perspective. just seems a little tacked on at the bottom, but I know we might not want to be advertising it too much.

**Review by jhurliman — CHANGES_REQUESTED** [review]
This is a good idea, but we need to either disallow raw shader usage (preferable, so we don't run into this with other three.js engine features) or provide helper GLSL so raw shaders can take use a logarithmic depth buffer in three.js.

This is blocked until labels work, but it's a lower priority since we fixed the demo layout z-fighting by changing the near plane.

**Comment by jtbandes** [comment]
Closing since we've found other workarounds to the original issues and this was blocked anyway on https://github.com/foxglove/three-text/issues/63.

**Pull request closed without merging**
