### PR TITLE
Use ToggleButtons for color scheme, timestamp format, and launch preference selectors

### PR DESCRIPTION
**Pull request by jtbandes**
**User-Facing Changes**
Not worth including in release notes

**Description**
image

### CODE REVIEW

**Comment by amacneil** [comment]
Cool. Couple thoughts:
- I feel like Dark, Light, System is a more natural order than having System in the middle?
- I would probably change it to `Use System` or `Follow System` rather than just `System`?

**Comment by foxymiles** [comment]
Looks nice! 👍 

Are there other places in the app where it would make sense to use a segmented control? It feels a bit odd that this is the only instance of it.

**Comment by jtbandes** [comment]
image

Only problem is it doesn't respond well to smaller sizes:

image

**Comment by jtbandes** [comment]
> Are there other places in the app where it would make sense to use a segmented control? It feels a bit odd that this is the only instance of it.


Stuff like this probably, where there are a small fixed number of choices:

image


I would also say we use it already in Settings...maybe we should make these look more consistent? I don't see a reason why the color scheme should be so different between Preferences and Panel Settings.

image

**Comment by foxymiles** [comment]
> > Are there other places in the app where it would make sense to use a segmented control? It feels a bit odd that this is the only instance of it.
> 
> Stuff like this probably, where there are a small fixed number of choices:
> 
> image
> 
> I would also say we use it already in Settings...maybe we should make these look more consistent? I don't see a reason why the color scheme should be so different between Preferences and Panel Settings.
> 
> image

Yeah I think the selected state of that toggle is also not clear with that coloring.

**Comment by foxymiles** [comment]
> image
> 
> Only problem is it doesn't respond well to smaller sizes:
> 
> image

Yeah responsiveness is tricky there.

**Comment by jtbandes** [comment]
🤦 didn't realize this is a thing: https://mui.com/material-ui/react-toggle-button/

**Comment by foxymiles** [comment]
> 🤦 didn't realize this is a thing: https://mui.com/material-ui/react-toggle-button/

I guess we could flip to the vertical mode on small screens?

**Comment by jtbandes** [comment]
That might be ideal but I don't want to add a ResizeDetector just for this purpose. I just enabled flex-wrap.
image

**Comment by foxymiles** [comment]
Should we make this full width to align with the other inputs?

**Comment by defunctzombie** [comment]
I am mixed on this. It looks ok but the dropdown seems to look more consistent in more situations. On narrow sidebars it remains a single dropdown and still obvious to interact with.

**Comment by jtbandes** [comment]
Updated to include toggle for timestamp format selection too.

**Comment by amacneil** [comment]
Waiting for @2metres to return before final 👍/👎

**Comment by 2metres** [comment]
I like the Color Scheme toggle but no sure about the timestamp toggle

**Comment by jtbandes** [comment]
How about these ones too?

image

**Comment by jtbandes** [comment]
Also looks nice if we use the primary color to better match the rest of the app: 
image

**Review by 2metres — APPROVED** [review]

**Pull request merged**
