### PR TITLE
Fail CI on unused exports

### PR DESCRIPTION
**Pull request by jtbandes**
**User-Facing Changes**
None

**Description**
Unused exports often point to dead code. Linting these in CI will help us remove unused code as it becomes unused.

### CODE REVIEW

**Comment by jtbandes** [comment]
Example error:
image

**Comment by defunctzombie** [comment]
@jtbandes we should delete it - the extension api uses a different api for the config. I think we just never fully ported things over to the `useConfig` without a panel id.

**Comment by amacneil** [comment]
Could this be done as an eslint rule rather than a separate script? That would be much cleaner for running it, using across projects, etc.

Similar request: https://github.com/typescript-eslint/typescript-eslint/issues/371

**Comment by jtbandes** [comment]
https://github.com/typescript-eslint/typescript-eslint/pull/1905

**Pull request merged**
