### PR TITLE
Fix: limit the plot history size in follow mode

### PR DESCRIPTION
**Pull request by defunctzombie**
**User-Facing Changes**
No visual changes. The app should be better about memory management when streaming data and a follow window size is configured.

**Description**
When streaming data, the plot would keep an infinite history of
messages even when a fixed follow window of some seconds was set. Keeping
the app conntected would result in the memory usage continuing to grow
and more dataset processing to occur as the messages array grew.

With this change, if there is a follow window, messages older than the
window are discarded.

### CODE REVIEW

**Comment by airfield20** [comment]
I am still having this issue running on version 1.0. Has this merge been included in the latest build?

**Comment by defunctzombie** [comment]
@airfield20 This change has been included in 1.0. In what way are you seeing this issue manifest?

**Comment by airfield20** [comment]
Foxglove studio goes from 100mb to 1.3gb ram usage over the course of 30 minutes when using the plotting tool with a 30 second x axis window set.

**Comment by defunctzombie** [comment]
Which data source are you using?

**Comment by defunctzombie** [comment]
@airfield20 Can you open a new issue and write up any notes you can on reproducing the issue? Helpful notes are: data source, operating system, which panels are involved. Anything that helps us isolate a reproducible case for this. That will help us track the problem and notify you of fixes.

**Comment by airfield20** [comment]
sure thing https://github.com/foxglove/studio/issues/2868

**Pull request merged**
