### PR TITLE
Switch sample dataset to nuscenes

### PR DESCRIPTION
**Pull request by defunctzombie**
**User-Facing Changes**
Clicking "Explore sample datasets" opens this new dataset and accompanying layout.

**Description**
This dataset has more images and markers to better display various capabilities of the app. Includes a new layout to display different app features.

Fixes: #2564

### CODE REVIEW

**Comment by defunctzombie** [comment]
Some issues I am seeing:

- [ ] 3d panel following of base_link appears to "wander" around on playback


https://user-images.githubusercontent.com/84792/147997830-10f2d768-5795-4212-b81f-f7457a01ecdd.mov

- [ ] Playing the file from GCS "stalls" the app. Seeking seems to put the app into a state where it feels "locked up"

**Comment by defunctzombie** [comment]
The wobble issue is fixed with an upgrade of @foxglove/regl-worldview

**Comment by amacneil** [comment]
Reviewing legal terms of use, will update when done.

**Review by amacneil — CHANGES_REQUESTED** [review]
Please add the following attribution to the Data Source sidebar:

> Adapted from nuScenes dataset. Copyright © 2020 nuScenes.
> https://www.nuscenes.org/terms-of-use

**Comment by defunctzombie** [comment]
https://github.com/foxglove/studio/issues/2589

**Comment by defunctzombie** [comment]
image
@amacneil

**Review by amacneil — APPROVED** [review]

**Pull request merged**
