### PR TITLE
Use binary search for merging {all,current}Frames in plot data

### PR DESCRIPTION
**Pull request by cfoust**
**User-Facing Changes**
Use a more efficient strategy for incorporating blocks of plot messages.

**Description**
Before, filtering old data was O(n); now we do a binary search to decide what data to keep.

I'm not sure whether this is the best solution, but it _greatly_ decreased this operation's contributions to slow rendering time (from several hundred milliseconds almost every frame to <1ms.)

### CODE REVIEW

**Comment by defunctzombie** [comment]
This is an appropriate change for what is happening with `currentFrame` - but _why_ is `currentFrame` so large that this was necessary?

**Review by foxymiles — APPROVED** [review]
Makes sense. Good find!

Can we use the sortedIndexBy stuff from lodash instead of writing our own search?

**Comment by cfoust** [comment]
interesting, it appears to be undocumented but it actually does use binary search: https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L4131
I had looked into whether lodash already had one, but their documentation did not mention it

**Comment by foxymiles** [comment]
They do document it here: https://lodash.com/docs/4.17.15#sortedIndex

But yeah they should really call this out more in the docs.

**Comment by cfoust** [comment]
I'm new to lodash (I prefer ramda) but it was unclear whether `sortedIndexBy` had the same semantics as `sortedIndex`; in my experience the `*By` can change behavior in unexpected ways

**Comment by foxymiles** [comment]
I prefer ramda too. We use it in console.

**Comment by cfoust** [comment]
made unnecessary by pending plot pipeline changes

**Pull request closed without merging**
