### PR TITLE
Use API key instead of username/password for Apple notarization

### LINKED ISSUE #1272: Use Apple API keys instead of raw credentials for notarization
Instead of appleId/appleIdPassword, we can pass appleApiKey/appleApiIssuer: https://github.com/electron/electron-notarize#method-notarizeopts-promisevoid

API keys can be generated as described here:
https://developer.apple.com/documentation/appstoreconnectapi/creating_api_keys_for_app_store_connect_api

You will need to put it in an appropriate directory on CI (such as `~/.appstoreconnect/private_keys`) for electron-notarize/altool to find it.

### PR DESCRIPTION
**Pull request by jtbandes**
**User-Facing Changes**
None

**Description**
Fixes #1272 along with https://github.com/foxglove/studio-release-builder/pull/7

API keys can be managed at https://appstoreconnect.apple.com/access/api

### CODE REVIEW

**Comment by defunctzombie** [comment]
LGTM assuming @amacneil we can make these api keys?

**Comment by amacneil** [comment]
I'm confused, because none of those exist in the release repo. Only:

- `APPLE_CERT_BASE64`
- `APPLE_CERT_PASSWORD`
- `APPLE_NOTARIZE_ID`
- `APPLE_NOTARIZE_PASSWORD`

**Comment by jtbandes** [comment]
See https://github.com/foxglove/studio-release-builder/pull/7

**Comment by amacneil** [comment]
Nevermind, derp. I didn't realize that we were mapping the secrets to differently named env vars.

With that in mind, can you rename these vars to `APPLE_NOTARIZE_FOO`?

**Pull request merged**
