### PR TITLE
Remove uses of mui Box component

### PR DESCRIPTION
**Pull request by 2metres**
**User-Facing Changes**
None

**Description**
Remove mui/Box component uses

### CODE REVIEW

**Review by jtbandes — APPROVED** [review]

**Comment by defunctzombie** [comment]
Do we have a way of making this a banned component?

**Comment by foxymiles** [comment]
Are we removing it because it uses sx under the hood?

**Comment by 2metres** [comment]
> Do we have a way of making this a banned component?

We did for Fluent UI at some point… don't see it now.

**Review by defunctzombie — APPROVED** [review]

**Comment by 2metres** [comment]
Closes FG-3392

**Pull request merged**
