### PR TITLE
Tint dark theme's greys to match paper color

### PR DESCRIPTION
**Pull request by 2metres**
**User-Facing Changes**
None

**Description**
Shift grey palette from neutral grey to slightly more blue. Makes tooltip background more harmonious with backgrounds

### CODE REVIEW

**Comment by jtbandes** [comment]
There's not really enough stories to show what the new colors look like in context, but this one looks worse (tooltip is basically the same color as the background):

image

**Comment by 2metres** [comment]
@jtbandes Do we want the the tooltip darker or lighter? I struggled to find the right contrast

**Comment by jtbandes** [comment]
Hard to say. Is there a reason we went with a dark tooltip in dark mode rather than inverting? What does mui do by default?

**Comment by jtbandes** [comment]
I guess that's what happens when you hold down the wrong modifier keys and hit enter

**Comment by 2metres** [comment]
> Hard to say. Is there a reason we went with a dark tooltip in dark mode rather than inverting? What does mui do by default?

I think MUI default is dark on dark, dark on light
```
alpha(theme.palette.grey[700], 0.92)
```

**Review by jtbandes — CHANGES_REQUESTED** [review]
Not entirely sure what problem we are solving here. I played with the preview deploy and I find the new tooltips in dark mode to be basically invisible. I do agree that the hue is more accurate to the other colors we use, but it has the effect of making them completely blend in to the point where I cannot see the tooltip border without bringing my face really close to the screen.

Before
image
image

After
image
image

**Review by jtbandes — APPROVED** [review]

**Pull request merged**
