### PR TITLE
Remove global styles as squashed commit

### PR DESCRIPTION
**Pull request by 2metres**
Hoping that this fixes some of my chromatic diff baselines to compare against main

### CODE REVIEW

**Comment by defunctzombie** [comment]
@2metres I pushed a commit which fixes the TimeBasedChartTooltip styling. It was largely a problem with conflicting styling in LegacyTable - another reason to do away with all these global evils.

**Comment by 2metres** [comment]
Massive amount of changes here, most of them just interim solutions until we can phase out <Dropdown>, <Button> and <TextField> to use fluentui components

**Comment by defunctzombie** [comment]
Good stuff. LGTM!

**Comment by amacneil** [comment]
Can you update PR title + description for PRs like this (I assume the actual description was in another PR somewhere). It's helpful for writing release notes and historical reference.

**Pull request merged**
