### PR TITLE
feat(Three.js panel): Custom background color settings

### PR DESCRIPTION
**Pull request by dudv**
**User-Facing Changes**
Custom background color settings option for three.js 3D panel

Screenshot 2022-04-20 at 14 59 47

### CODE REVIEW

**Comment by dudv** [comment]
@jhurliman Could you please take a look?

**Comment by dudv** [comment]
The new API seems much more verbose, especially calling private methods like `__updatePanelSettingsTree`.  Is it the right way of using it? @jhurliman

**Comment by foxymiles** [comment]
@dudv Are you referring to this with your comment about casting?

```    (context as unknown as any).__updatePanelSettingsTree({
```

Hiding this as `__updatePanelSettingsTree` is just a temporary measure so we can use this in our extension panels and work out the details of the API before we commit to making this a public API we encourage people to use. Once we're happy with the details we'll make this a proper method on the extension panel context.

**Comment by jhurliman** [comment]
This is implemented

**Pull request closed without merging**
