### PR TITLE
Build docker image GitHub action

### PR DESCRIPTION
**Pull request by bertaveira**
**Motivation**
As we saw the necessity to have an image up to date with the foxglove I decided to make it automatically build the image and push it. It has worked for us (although in gitlab not github) so I thought it would be nice to make it official and make it public so everyone can have access to an official, automatically released and up to date image. 

The idea would be to have an official foxglove account on docker hub and replace my personal one in the CI so that on every release it builds the image and tags with the version number as well as replaces the latest tag.

**Description**
What this pull does is add a new Github action job where it builds the docker image for multi-architecture and then pushes it to docker hub. Right now it is pushing ot my personal account but if this is of interest to foxglove as much as it is to me the idea would be to make it push to an official docker hub account of foxglove.

Currently it is building for 2 platforms but more could be added:
- linux/amd64 - Regular Linux x86
- linux/arm64 - The ARM version supported by ROS official docker images (ARM v8 such as Apple M1 and latest Raspberry Pi's)

The images built are tagged with the version number as well as the `:latest` tag. This way the latest is always the most recent version of foxglove studio, but everyone can also choose a specific version if they so desire.

**Tests**
To test if the action was working i did some releases on my fork in a different branch. The reason I did them on a different branch is because the release CI also commits to the branch ("Bump dev" job). Since I didn't want this pull messing with versions due to my tests, they were done in a separate branch called ` bernardo/build-docker-action` (sorry for the confusing branch names). You can check the actions and releases I made to validate that it works as well as my docker hub repository ([here](https://hub.docker.com/repository/docker/bertaveira/foxglove/general)).

To note that building both images (amd64 and arm64) takes about 1h.

**Adaptations needed**

1. Create a foxglove docker account
2. Add docker hub credentials as secret variables on github (`DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`) and replace name of docker image in the `post-release.yml` file. I can do this last step on my branch but the account needs to be created first.

### CODE REVIEW

**Comment by defunctzombie** [comment]
This is great! We'd absolutely be interested in publishing a pre-built image.

Lets go with the github container registry (https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages) which lets us host the images with github. And name the image `foxglove/studio`.

**Comment by bertaveira** [comment]
@defunctzombie I have made the changes to make it work. It has been tested in a seperate branch of my fork ( `bernardo/test-docker-action` ). For testing I made a fake release called `test14`.

To make it work 2 new secret variables had to be added to the github ( `GHCR_USER` and `GHCR_TOKEN` ) respectively for the user and authentication token used to push the docker image to the github container registry.

**Comment by defunctzombie** [comment]
@bertaveira My understanding from https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages is that those lines should be:

```
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
```

Did that not work when you tried it in your repo?

**Comment by bertaveira** [comment]
> @bertaveira My understanding from https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages is that those lines should be:
> 
> ```
> username: ${{ github.actor }}
> password: ${{ secrets.GITHUB_TOKEN }}
> ```
> 
> Did that not work when you tried it in your repo?

That could work but using the `${{ github.actor }}` means that the user used is the one that triggered the workflow. Therefore the token would have to be that persons personal token and have to be inserted manually as a repository secret. I don't know if this is desired because only one user would have to be allowed to create releases.

**Comment by bertaveira** [comment]
Sorry my bad. Just tried and the `${{ secrets.GITHUB_TOKEN }}` variable is indeed automatically assigned. I am testing right now and I'll make the changes as soon as I confirm it works

**Comment by amacneil** [comment]
I'm happy to review + merge this soon. I'm pretty sure GITHUB_TOKEN should work once this is actually merged, since the default Github user has write access to the container registry for trusted (i.e. non-PR) workflows.

**Comment by bertaveira** [comment]
It unfortunately failed to push the images. I will investigate further tomorrow. It succeeds in the login stage of the job but on the buildx command after generating the omages in the last step pushing the images it gets a premission error:

```
#28 pushing layers
#28 ...

#29 [auth] bertaveira/studio:pull,push token for ghcr.io
#29 DONE 0.0s

#28 exporting to image
#28 ...

#30 [auth] bertaveira/studio:pull,push token for ghcr.io
#30 DONE 0.0s

#28 exporting to image
#28 pushing layers 0.4s done
#28 ERROR: unexpected status: 403 Forbidden
------
 > exporting to image:
------
error: failed to solve: unexpected status: 403 Forbidden
Error: buildx failed with: error: failed to solve: unexpected status: 403 Forbidden
```

**Comment by bertaveira** [comment]
Ok now it is working pushing to the github container registry using the GITHUB_TOKEN. One thing that is needed is to go to the specific container and give permission for actions of a certain repository to push to it. 

Instructions here: https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio

**Comment by amacneil** [comment]
Thank you!

**Review by amacneil — APPROVED** [review]

**Pull request merged**
