### PR TITLE
Remove ROS 2 native connector

### PR DESCRIPTION
**Pull request by jhurliman**
**User-Facing Changes**
- The ROS 2 native connector is removed in the desktop version of Studio. Connecting via rosbridge is the preferred option for ROS 2 robots

**Description**
Large message support over DDS/RTPS is significantly more complex than messages that fit in a single UDP datagram since RTPS relies heavily on tuning knobs and heuristics to prevent retry floods and achieve real-time frame rates for image or pointcloud-sized messages. It's unlikely the @foxglove/rtps library will achieve the level of performance needed to reliably receive sensor message streams in the near future, so this PR removes the option from Studio for now.

Addresses #4704, #4698, #3272, #1661, #2614.

### CODE REVIEW

**Comment by jtbandes** [comment]
Rather than just removing the feature suddenly, we should probably follow a deprecation and feature flag process like we are doing with the old3d panel.

**Comment by amacneil** [comment]
Not sure whether this was discussed in Slack or this PR is just coming out of the blue. But cc @banisadr to think about because we have quite a few users of ROS 2 native connections.

**Comment by defunctzombie** [comment]
> RTPS relies heavily on tuning knobs and heuristics to prevent retry floods and achieve real-time frame rates for image or pointcloud-sized messages.

@jhurliman could you elaborate on this here so we can understand some of the nuances and gotchas involved in updating our RTPS library to support large messages. Some things I would find helpful are links to code or docs that show the complexity of the knobs or heuristics that we'd have to replicate or the RTPS documentation/spec for sending large messages.

**Comment by banisadr** [comment]
To be clear, you're not saying that the ROS 2 native connection route is a broken one right? Just that it's less performant with large messages (& what constitutes a large message in this case)?

**Comment by jhurliman** [comment]
@banisadr I am saying it is broken. You might see one or two camera frames, then we never receive 100% of the packets to constitute an additional full frame so the connection appears broken while your network is being flooded with packets.

**Comment by jhurliman** [comment]
> > RTPS relies heavily on tuning knobs and heuristics to prevent retry floods and achieve real-time frame rates for image or pointcloud-sized messages.
> 
> @jhurliman could you elaborate on this here so we can understand some of the nuances and gotchas involved in updating our RTPS library to support large messages. Some things I would find helpful are links to code or docs that show the complexity of the knobs or heuristics that we'd have to replicate or the RTPS documentation/spec for sending large messages.

Here is the [official spec](https://www.omg.org/spec/DDSI-RTPS/2.2/PDF) where large message sending is described; see the sections describing `DataFrag`, `HeartbeatFrag`, and `NackFrag`. The description is fairly bare-bones and @foxglove/rtps I think implements what is described in the spec. When receiving a large message, FastDDS will send some percentage of the packets making up a large `sensor_msgs/Image` message but then pause as if it's waiting for ACKs. We are sending ACKs and they do work sometimes, but maybe one in five attempts. I've tried many different patterns of how to coax the sender to deliver more packets, some more successful than others. Still, eventually, it will fall behind and I have not figured out how to get the data flow back on track once a packet has been dropped or we fall behind. I don't have any pointers to FastDDS or CycloneDDS code on how to "make it work" (otherwise I might be further along!).

**Comment by banisadr** [comment]
From discussion today: Plan forward is to hold off on this 🔪 until we have a 1st class bridge which will act as our happy path. We'll 🔪 the native connector once that's available.

**Comment by defunctzombie** [comment]
Closing this PR until it is time to get around to it. The plan is to deprecate in stages with warnings and a feature flag.

**Pull request closed without merging**
