### PR TITLE
Improves empty layout state

### PR DESCRIPTION
**Pull request by foxymiles**
**User-Facing Changes**
Improves empty layout state.

**Description**
This fixes remaining issues with https://github.com/foxglove/studio/pull/4578
Closes https://github.com/foxglove/studio/pull/4578

### CODE REVIEW

**Review by jtbandes — APPROVED** [review]

**Comment by defunctzombie** [comment]
"Create a new layout" creates a new default layout for me. Is the intent to have that happen rather than drop the user into the panel selection grid I see when I click "+" in the layout panel?

**Review by defunctzombie — APPROVED** [review]

**Comment by foxymiles** [comment]
@defunctzombie I'm not sure. It would of course be easy to create an empty layout instead if you think that's better UX.

**Comment by defunctzombie** [comment]
@foxymiles probably worth doing a demo at upcoming product review and seeing what the beehive thinks and then merging based on that feedback.

**Comment by amacneil** [comment]
When I hit "create a new layout" let's create an empty one rather than default layout.

**Pull request merged**
