### PR TITLE
Rename constants.ts to version.ts

### PR DESCRIPTION
**Pull request by amacneil**
Appease @defunctzombie

### CODE REVIEW

**Comment by defunctzombie** [comment]
Anything blocking this?

**Comment by amacneil** [comment]
No I just need to remember to add `SENTRY_PROJECT` to our release env

**Comment by amacneil** [comment]
Unclear why this is failing integration test, requires investigation

**Comment by defunctzombie** [comment]
> Unclear why this is failing integration test, requires investigation

Have you tried making a prod build manually?

**Comment by amacneil** [comment]
> Have you tried making a prod build manually?

No, that's part of the "needs investigation". Will try now.

**Pull request merged**
