### PR TITLE
feat(mcap-support): cbor channel decoder

### PR DESCRIPTION
**Pull request by jon-chuang**
**User-Facing Changes**
Support decoding message channels with "cbor" encoding

**Description**
Support decoding message channels with "cbor" encoding

Fix: https://github.com/orgs/foxglove/discussions/405

### CODE REVIEW

**Comment by jon-chuang** [comment]
Next step: should we allow jsonschema also allow for "cbor" encoding?

> JSON Schema is only defined over JSON documents. However, any document or memory structure that can be parsed into or processed according to the JSON Schema data model can be interpreted against a JSON Schema, including media types like [CBOR](https://json-schema.org/draft/2020-12/json-schema-core.html#RFC7049) [[RFC7049](https://json-schema.org/draft/2020-12/json-schema-core.html#RFC7049)].

See: https://json-schema.org/draft/2020-12/json-schema-core.html

**Comment by jtbandes** [comment]
Please see prior discussion here: https://github.com/foxglove/studio/pull/4957

**Comment by jtbandes** [comment]
@jon-chuang We're open to accepting this feature (for schemaless channels only, for now) but it needs to start with a PR to the mcap repo to update the [registry of well-known encodings](https://github.com/foxglove/mcap/blob/main/website/docs/spec/registry.md). Would you be willing to make that PR so we can discuss there?

**Comment by jon-chuang** [comment]
We are closing the PR for now as there is no concrete user request and lack of further interest to develop.

The author would like to thank the maintainers for their support despite this unfortunate ending.

**Pull request closed without merging**
