### PR TITLE
Remove ModalHost/ModalContext, fix useConfirm in dev mode

### PR DESCRIPTION
**Pull request by jtbandes**
**User-Facing Changes**
None

**Description**
Update `useConfirm`, `usePrompt`, and `ProblemsList` to keep the modal element in `useState` rather than in the `ModalHost`. The caller of `useConfirm`/`usePrompt` is now passed a modal element in addition to a confirm/prompt function and is responsible for rendering that element in the tree. This allows for the deletion of `ModalHost` & `ModalContext`.

Fixes https://github.com/foxglove/studio/issues/5041
Fixes FG-1140

### CODE REVIEW

**Review by foxymiles — APPROVED** [review]
I don't think I've seen JSX elements in `useState` before. Is that an encouraged practice?

**Comment by jtbandes** [comment]
Not sure I’ve ever heard it encouraged or discouraged — do you think it could be problematic?

**Comment by foxymiles** [comment]
> Not sure I’ve ever heard it encouraged or discouraged — do you think it could be problematic?

It's certainly unconventional. Did you consider using a React portal for this? That's the most common solution I've seen for this kind of thing.

**Review by defunctzombie — COMMENTED** [review]
How does this prevent modals from inheriting the z-index and other styling elements of the container you put them in? I suppose that would be true of any place you use a MUI `<Modal>` and it is something that the modal itself handles internally?

**Comment by jtbandes** [comment]
> Did you consider using a React portal for this? That's the most common solution I've seen for this kind of thing.

I don’t think this comment is relevant to the useState issue? Isn’t it common to render mui Modals without a portal?

> How does this prevent modals from inheriting the z-index and other styling elements of the container you put them in? I suppose that would be true of any place you use a MUI `<Modal>` and it is something that the modal itself handles internally?

Same

**Pull request merged**
