### PR TITLE
<feat>:panels support collapse and expand

### PR DESCRIPTION
**Pull request by smbera**
**User-Facing Changes**

Ability to make panels collapsible and expandable

**Description**
https://github.com/orgs/foxglove/discussions/621

https://user-images.githubusercontent.com/23401125/215308670-00e4ac00-2eb7-419d-b6c8-00831a58ee14.mp4

### CODE REVIEW

**Comment by banisadr** [comment]
Hi @smbera we've had a couple of internal discussions about this PR and we're not going to be able to accept it at this time. While it is a cool idea, the mosaic handling code (particularly in layouts with tabs) is fairly tricky to maintain and this significantly increases the test surface area we would need to cover. 

Its a very cool idea however, and you've inspired us to add it to our list of features to consider if/when we rewrite our mosaic handling.

**Comment by smbera** [comment]
> 
I'm so sorry to hear that. But let me make it clear here that for the sake of simplicity, the panel of the tab layout in the code has been disabled from folding. Finally, I respect your decision. Thank you!

**Comment by smbera** [comment]
> Hi @smbera we've had a couple of internal discussions about this PR and we're not going to be able to accept it at this time. While it is a cool idea, the mosaic handling code (particularly in layouts with tabs) is fairly tricky to maintain and this significantly increases the test surface area we would need to cover.
> 
> Its a very cool idea however, and you've inspired us to add it to our list of features to consider if/when we rewrite our mosaic handling.



> 



> Hi @smbera we've had a couple of internal discussions about this PR and we're not going to be able to accept it at this time. While it is a cool idea, the mosaic handling code (particularly in layouts with tabs) is fairly tricky to maintain and this significantly increases the test surface area we would need to cover.
> 
> Its a very cool idea however, and you've inspired us to add it to our list of features to consider if/when we rewrite our mosaic handling.

I'm so sorry to hear that. But let me make it clear here that for the sake of simplicity, the panel of the tab layout in the code has been disabled from folding. Finally, I respect your decision. Thank you!

**Comment by smbera** [comment]
> Hi @smbera we've had a couple of internal discussions about this PR and we're not going to be able to accept it at this time. While it is a cool idea, the mosaic handling code (particularly in layouts with tabs) is fairly tricky to maintain and this significantly increases the test surface area we would need to cover.
> 
> Its a very cool idea however, and you've inspired us to add it to our list of features to consider if/when we rewrite our mosaic handling.

I'm so sorry to hear that. But let me make it clear here that for the sake of simplicity, the panel of the tab layout in the code has been disabled from folding. Finally, I respect your decision. Thank you!

**Pull request closed without merging**
